### ISSUE TITLE
Does this project concern with higher level abstractions for keyboard?

### ISSUE THREAD

**Issue by rathod-sahaab** [dlkj/usbd-human-interface-device#133]
I am making a device to get some words from `Lorem Ipsum`... and send it to the PC

Circuit python hid has this [write(string: str, delay: float = None) → None](https://docs.circuitpython.org/projects/hid/en/latest/api.html#adafruit_hid.keyboard_layout_us.KeyboardLayoutUS.write)

Does this library concern with this or is it out of scope.

**Comment by dlkj** [comment]
Hi, there isn't a high level method for doing this in the library at the moment. You could either write your own code that could use this library to send the individual characters or you could extend one of the managed keyboards to add this functionality.

**Comment by rathod-sahaab** [comment]
Thanks just needed clarification, will add code once I am done, might help someone out.
