### ISSUE TITLE
Example on multi-device + hid raw device

### ISSUE THREAD

**Issue by haata** [dlkj/usbd-human-interface-device#137]
I'm somewhat interested in using this crate to replace what I've done in https://github.com/kiibohd/kiibohd-core/tree/main/kiibohd-usb.

The main complication is that I also have to deal with a raw hid device as well and it's not clear how to use raw hid with this crate.

(this is where raw hid is used https://github.com/kiibohd/kiibohd-core/blob/main/kiibohd-usb/src/lib.rs#L782).

**Comment by dlkj** [comment]
I'd be happy to help. Can you point me of some example of `raw hid` you are using and I can see how we can accommodate it. My assumption is that we could build a device that exposes a subset of the `usbd_human_interface_device::interface::InterfaceClass` methods like `get_report` and `set_report`

**Comment by dlkj** [comment]
Here is a quick example based on the descriptor you are using with kiibohd: [hid_io.rs](https://github.com/dlkj/usbd-human-interface-device/blob/hid-io/examples/src/bin/hid_io.rs)

I gave it a quick test with [todbot/hidapitester](https://github.com/todbot/hidapitester) and it seems to work fine.
