### ISSUE TITLE
USB Keyboard and USB Serial at the same time

### ISSUE THREAD

**Issue by codekrolik2** [dlkj/usbd-human-interface-device#149]
Hello guys, I'm writing a project for pi pico and I'd like to have the board to function as both Serial device for debug output and a keyboard.
I was able to achieve that in Arduino simply by calling 
```
  Keyboard.begin(KeyboardLayout_en_US);
  Serial.begin(115200);
  etc.
```
However, when I'm trying to replicate the same in Rust it doesn't work simultaneously.
While I can successfully make the board work as Keyboard or Serial, I can't combine the two - in this case lsusb doesn't show any USB devices.
Do you know what's causing this limitation or how it can be overcome?

**Comment by dlkj** [comment]
Hey codekrolik2,

I may be able to help you if you link to an example repo showing the code you are trying to use.

Here is some of my older code, that predates this library, showing how you can use a serial device and hid at the same time: https://github.com/dlkj/macropad-rust/blob/main/cross/app/src/usb.rs

The key bit is to pass both the hid and serial devices to the `poll` function:

```rust
      if self
            .usb_device
            .poll(&mut [&mut self.serial_port, &mut self.keyboard])
        {
            let mut buf = [0u8; 64];
            match self.serial_port.read(&mut buf) {
                Err(_e) => {}
                Ok(_count) => {}
            }

            let mut buf = [0u8; 64];
            match self.keyboard.pull_raw_output(&mut buf) {
                Err(_e) => {}
                Ok(_count) => {}
            }
        }
```

**Comment by codekrolik2** [comment]
I'm doing the following in my test:

**Comment by codekrolik2** [comment]
Let me study your code and try to adopt, thank you very much for the pointer!

**Comment by dlkj** [comment]
You don't need two instances of `UsbDeviceBuilder`. Try something like:

```rust
    // Set up the USB Communications Class Device driver
    let mut serial = SerialPort::new(usb_bus_allocator);

    let mut keyboard = UsbHidClassBuilder::new()
        .add_device(usbd_human_interface_device::device::keyboard::BootKeyboardConfig::default())
        .build(usb_bus_allocator);

    // Create a USB device with a fake VID and PID
    let mut usb_dev_keyboard = UsbDeviceBuilder::new(usb_bus_allocator, UsbVidPid(0x1209, 0x0001))
        .manufacturer("flower-org")
        .product("Boot Keyboard")
        .serial_number("Phraser")
        .device_class(0x00)
        .build();
```

**Comment by codekrolik2** [comment]
Worked like a charm.
Thank you very much!
