### ISSUE TITLE
Usage of report_idle hash map

### ISSUE THREAD

**Issue by jedrzejboczar** [dlkj/usbd-human-interface-device#77]
I noticed that in `RawInterface` you are [using FnvIndexMap](https://github.com/dlkj/usbd-human-interface-device/blob/8b3c55b0a312115040f8574f1b6c701693cc82d4/src/interface/raw.rs#L32) to store idle times received from SET_IDLE requests. Is it actually needed to use a hash map there? As far as I understand report IDs will always start from 0, so a simple array would seem sufficient, something like `[Option<u8>; 32]` (64 B, could be even smaller by using `[u8; 32]` along with a `u32` bitmap of "existing" entries to get 36 B).  Also, using 32 entries seems like an overkill, as most often there will be just a single report, and it should be very rare to have more that 4. 

My question is due to the fact that hashing seems unnecessary (vs simple array indexing), and additionally this hash map takes significant amount of space in the structure (260 B out of 460 B), which is then multiplied by the number of HID interfaces. Here's how the size looks like:
![Screenshot from 2022-11-16 20-57-31](https://user-images.githubusercontent.com/16623787/202282234-1673e78a-a4e2-44c4-9bbc-85bcbcd6b49c.png)

Do you think changing this makes sense? Or is there some other reason for using a hash map?

---

Another potential optimization could be defining the size of `control_*_report_buffer` using const generics to pass max size of the report. But this would add some complexity to the rest of code base due to new generic parameter. 

And an unrelated question: why writing a duplicate report [causes a tick](https://github.com/dlkj/usbd-human-interface-device/blob/8b3c55b0a312115040f8574f1b6c701693cc82d4/src/interface/managed.rs#L89)? Non-duplicates are rare, so wouldn't that mean that the time passes almost two times faster (e.g. 1kHz write_report + 1kHz tick())?

**Comment by dlkj** [comment]
The duplicate `tick()` is left over from the transition away from using `embedded_time` timers to track the timeout. I'll remove it.

**Comment by dlkj** [comment]
As usual this comes down to a balance of size, ergonomics and correctness.

The HID spec doesn't specifies that the report id is an unsigned byte and can't be zero. There are not restriction on how they are picked and how many a device has. While I agree your suggestions around having a small number of report IDs is practical, it wouldn't work with arbitrary valid HID descriptors.

The IndexMap is overkill from both a size and performance cost in almost all common cases. I would expect that this could be transitioned to a Vec or similar with minimal changes.

The buffers could also be parameterised.

At the moment the library is pretty good at letting someone implement an arbitrary HID quickly and easily with good ergonomics or use one of the off-the-shelf examples quickly. I agree that concrete interfaces, like the keyboards, where the descriptor and report sizes are well defined could be optimised for size.
